# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nota', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Work at home', 'Work at home'), ('Repeat', 'Repeat'), ('Continue', 'Continue'), ('No Show', 'No Show')], default='Good', max_length=15)),
                ('comentarios', models.CharField(blank=True, max_length=35)),
                ('firma_alumno', models.BooleanField()),
            ],
            options={
                'verbose_name': 'record acad\xe9mico',
                'verbose_name_plural': 'records acad\xe9micos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('numero_contrato', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(blank=True, max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('cedula', models.CharField(blank=True, max_length=10, verbose_name='C\xe9dula')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('direccion_domicilio', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('celular', models.CharField(blank=True, max_length=10)),
                ('empresa', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=20)),
                ('direccion_empresa', models.CharField(blank=True, max_length=30)),
                ('telefono_empresa', models.CharField(blank=True, max_length=10)),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creaci\xf3n')),
                ('duracion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_maxima', models.PositiveSmallIntegerField(default=6)),
                ('tipo_nivel', models.TextField(default='xx', max_length='2')),
                ('tipo_leccion', models.PositiveSmallIntegerField(default=0)),
                ('max_tipo', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='c\xe9dula')),
                ('foto', models.ImageField(default='estudiante_perfil/master.jpg', upload_to='estudiante_perfil/')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('direccion_domicilio', models.CharField(blank=True, max_length=25)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('fecha_de_inicio', models.DateField()),
                ('fecha_de_expiracion', models.DateField()),
                ('lugar_de_trabajo', models.CharField(blank=True, max_length=30)),
                ('contacto_de_emergencia', models.CharField(blank=True, max_length=30)),
                ('relacion_de_contacto_de_emergencia', models.CharField(blank=True, max_length=30, verbose_name='relaci\xf3n de contacto de emergencia')),
                ('telefono_de_contanto_de_emergencia', models.CharField(blank=True, max_length=10, verbose_name='tel\xe9fono de contacto de emergencia')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Limitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Estudiante')),
            ],
            options={
                'verbose_name': 'limitacione',
                'verbose_name_plural': 'limitaciones',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=2)),
                ('leccion', models.IntegerField()),
                ('tema', models.CharField(max_length=35, verbose_name='Actividad')),
            ],
            options={
                'ordering': ['nivel'],
                'verbose_name': 'nivel',
                'verbose_name_plural': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, verbose_name='C\xe9dula')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('horario_lunes_inicio_manana', models.TimeField(blank=True, null=True)),
                ('horario_lunes_fin_manana', models.TimeField(blank=True, null=True)),
                ('horario_lunes_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('horario_lunes_fin_tarde', models.TimeField(blank=True, null=True)),
                ('horario_martes_inicio_manana', models.TimeField(blank=True, null=True)),
                ('horario_martes_fin_manana', models.TimeField(blank=True, null=True)),
                ('horario_martes_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('horario_martes_fin_tarde', models.TimeField(blank=True, null=True)),
                ('horario_miercoles_inicio_manana', models.TimeField(blank=True, null=True)),
                ('horario_miercoles_fin_manana', models.TimeField(blank=True, null=True)),
                ('horario_miercoles_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('horario_miercoles_fin_tarde', models.TimeField(blank=True, null=True)),
                ('horario_jueves_inicio_manana', models.TimeField(blank=True, null=True)),
                ('horario_jueves_fin_manana', models.TimeField(blank=True, null=True)),
                ('horario_jueves_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('horario_jueves_fin_tarde', models.TimeField(blank=True, null=True)),
                ('horario_viernes_inicio_manana', models.TimeField(blank=True, null=True)),
                ('horario_viernes_fin_manana', models.TimeField(blank=True, null=True)),
                ('horario_viernes_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('horario_viernes_fin_tarde', models.TimeField(blank=True, null=True)),
                ('horario_sabado_inicio_manana', models.TimeField(blank=True, null=True)),
                ('horario_sabado_fin_manana', models.TimeField(blank=True, null=True)),
                ('horario_sabado_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('horario_sabado_fin_tarde', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_programa', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Estado')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Estudiante', to='masterkey.Estudiante')),
            ],
            options={
                'verbose_name': 'seguimiento',
                'verbose_name_plural': 'seguimientos',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad', models.IntegerField()),
                ('nivel', models.CharField(max_length=12)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='alumnos', to='masterkey.Estudiante')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Ciudad')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Profesor')),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=35)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('estudiante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masterkey.Estudiante')),
                ('profesor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masterkey.Profesor')),
                ('sede', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masterkey.Sede')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Sede'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Nivel'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Programa'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='masterkey.Estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Profesor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Sede'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_estudiante',
            field=models.ManyToManyField(blank=True, related_name='tipo_estudiante', to='masterkey.Nivel'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='beneficiarios',
            field=models.ManyToManyField(to='masterkey.Estudiante'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sede_firma_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Sede'),
        ),
        migrations.AddField(
            model_name='academic_rank',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Estudiante'),
        ),
        migrations.AddField(
            model_name='academic_rank',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Nivel'),
        ),
        migrations.AddField(
            model_name='academic_rank',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterkey.Profesor'),
        ),
    ]
